AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  automation

Globals:
  Function:
    Timeout: 3

Resources:
  TriggerGlueJobFromS3Function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  TriggerGlueJobFromS3Function:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt TriggerGlueJobFromS3Function.Arn
  TriggerGlueJobFromS3FunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt TriggerGlueJobFromS3FunctionRole.Arn
